# Generated by Django 4.0.4 on 2022-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=6)),
            ],
        ),
    ]
